# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_squashed_0025_formation_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='barrette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
