# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20170903_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouverture',
            name='nom_session',
            field=models.CharField(default='Toussaint', max_length=50, unique='True'),
        ),
        migrations.AlterUniqueTogether(
            name='ouverture',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ouverture',
            name='barrette',
        ),
    ]
