# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_enseignant_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matiere',
            field=models.CharField(default='??', max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='salle',
            field=models.CharField(default='??', max_length=50),
        ),
    ]
