# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20170905_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='invalide',
            field=models.BooleanField(default=False),
        ),
    ]
