# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_cours_invalide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
