# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_auto_20170925_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='barrettes',
            field=models.ManyToManyField(blank=True, related_name='b', to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='indirects',
            field=models.ManyToManyField(blank=True, related_name='i', to='votes.Barrette'),
        ),
    ]
