# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_etudiant_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouverture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='ouverture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Ouverture'),
        ),
    ]
