# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_auto_20161007_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
