# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_barrette'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='barrette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='barrettes',
            field=models.ManyToManyField(to='votes.Barrette'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='barrette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
        ),
        migrations.AddField(
            model_name='horaire',
            name='jour',
            field=models.IntegerField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi')], default=1),
        ),
        migrations.AddField(
            model_name='ouverture',
            name='nom_session',
            field=models.CharField(default='Toussaint', max_length=50),
        ),
        migrations.AlterField(
            model_name='cours',
            name='ouverture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Ouverture'),
        ),
    ]
