# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_cours_lessaveurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='lessaveurs',
        ),
    ]
