# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_remove_cours_lessaveurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouverture',
            name='barrettes',
            field=models.ManyToManyField(blank=True, related_name='bb', to='votes.Barrette'),
        ),
        migrations.AddField(
            model_name='ouverture',
            name='visible',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
