# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20161130_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.IntegerField(choices=[(1, 'S, ES, L (scientifique, économique & social, littéraire)'), (2, 'STMG (sciences et techniques de management & gestion)')], default=1)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Etudiant')),
                ('ouverture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Ouverture')),
            ],
        ),
    ]
