# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_auto_20181005_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Etudiant')),
            ],
        ),
    ]
