# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0013_auto_20161204_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionOrientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.CoursOrientation')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Etudiant')),
            ],
        ),
    ]
