# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_auto_20190126_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='barrette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Enseignant'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Formation'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Horaire'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='ouverture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Ouverture'),
        ),
        migrations.AlterField(
            model_name='coursorientation',
            name='barrette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='coursorientation',
            name='cop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Cop'),
        ),
        migrations.AlterField(
            model_name='coursorientation',
            name='prof',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.Enseignant'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='barrette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='auteur',
            field=models.ForeignKey(blank=True, help_text='le dernier prof à avoir modifié le titre ou le contenu', null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.Enseignant'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='barrette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='barrette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Cours'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Etudiant'),
        ),
        migrations.AlterField(
            model_name='inscriptionorientation',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.CoursOrientation'),
        ),
        migrations.AlterField(
            model_name='inscriptionorientation',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Etudiant'),
        ),
        migrations.AlterField(
            model_name='orientation',
            name='etudiant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.Etudiant'),
        ),
        migrations.AlterField(
            model_name='orientation',
            name='ouverture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Ouverture'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='barrette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.Barrette'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Cours'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.Etudiant'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='ouverture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.Ouverture'),
        ),
    ]
