# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_inscriptionorientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursorientation',
            name='prof',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Enseignant'),
        ),
    ]
