# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_coursorientation_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrette',
            name='classesJSON',
            field=models.CharField(default="'[]'", max_length=500, verbose_name='classes'),
        ),
    ]
