# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0016_barrette_classesjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrette',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
