# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0017_auto_20170819_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursorientation',
            name='barrette',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='barrette',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ouverture',
            name='barrette',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='barrette',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='barrette',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
            preserve_default=False,
        ),
    ]
