# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0018_auto_20170819_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='enseignant',
            unique_together=set([('uid', 'salle')]),
        ),
    ]
