# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0019_auto_20170820_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
