# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0020_enseignant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
