# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0021_auto_20170828_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
