# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0023_auto_20170828_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire',
            name='barrette',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='votes.Barrette'),
            preserve_default=False,
        ),
    ]
