# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0024_horaire_barrette'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='auteur',
            field=models.ForeignKey(blank=True, help_text='le dernier prof à avoir modifié le titre ou le contenu', null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.Enseignant'),
        ),
    ]
