# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='classe',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
