# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20160923_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name_plural': 'cours'},
        ),
        migrations.AddField(
            model_name='cours',
            name='capacite',
            field=models.IntegerField(default=18),
        ),
    ]
