# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20160925_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='uid',
            new_name='uidNumber',
        ),
        migrations.AlterField(
            model_name='formation',
            name='public_designe',
            field=models.BooleanField(default=False, verbose_name='Public désigné'),
        ),
    ]
